pipeline{
    agent any

    stages{
        stage('Deploy') {
            steps {
                sh '''
                oc project eggodm-deploy-strategies
                oc start-build greeting-service --follow --wait
                '''
            }
        }
    }
}